package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"atomgit.com/hust-open-atom-club/atomgit-cli/internal/docsgen"
	rootcmd "atomgit.com/hust-open-atom-club/atomgit-cli/pkg/cmd/root"
	"atomgit.com/hust-open-atom-club/atomgit-cli/pkg/cmdutil"
)

const defaultOutput = "docs/command-reference.md"

func main() {
	output := flag.String("output", defaultOutput, "path to the generated Markdown file")
	check := flag.Bool("check", false, "compare generated output with the existing file")
	flag.Parse()

	root, err := rootcmd.NewCmdRoot(&cmdutil.Factory{})
	if err != nil {
		fatalf("create command tree: %v", err)
	}
	var generated bytes.Buffer
	if err := docsgen.Generate(&generated, root); err != nil {
		fatalf("generate command reference: %v", err)
	}

	if *check {
		current, err := os.ReadFile(*output)
		if err != nil {
			fatalf("read %s: %v", *output, err)
		}
		if !bytes.Equal(current, generated.Bytes()) {
			fatalf("%s is out of date; run go run ./scripts/generate-command-reference", *output)
		}
		return
	}

	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		fatalf("create output directory: %v", err)
	}
	if err := os.WriteFile(*output, generated.Bytes(), 0o644); err != nil {
		fatalf("write %s: %v", *output, err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "generate-command-reference: "+format+"\n", args...)
	os.Exit(1)
}
